configuration: 2
language: en

# Purchase cost
# This function needs Vault enabled.
claim-cost: 2000.0

# Protection for the claimed villagers
# Set to true if you want those getting protected.
protection:
  player: true
  zombie: false
  pillager: false
  falling-block: true
  suffocation: true
  fall: true
  fire: true
  explode: true
  poison: true

deny-sound: ENTITY_VILLAGER_NO

hooks:
  Vault: true